<?php
/* LiangLee News Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee News Manager
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File settings.php
 */
/**
* Get Version
**/ 
$plug_ver = LiangLee_version('LiangLeeNews');
$plug_rel = LiangLee_release('LiangLeeNews');

/**
* Resgister Languages
**/
$lee_news_text = elgg_echo('leenews:1');

/**
* Resgister Settings
**/

$lee_news = elgg_view("input/longtext", array(
"name" => "params[LiangLee_news]", 
"placeholder" => "This is news",
"value" => $vars['entity']->LiangLee_news
));
$lee_news_onoff = elgg_view('input/dropdown', array(
    'name' => 'params[LiangLee_news_onoff]',
    'value' => $vars['entity']->LiangLee_news_onoff,
    'options_values' => array(
	'1' => 'Enable News', 
	'0' => 'Disable News'
	)));
$settings = <<<__HTML

    <div>
		<p><i>$lee_news_text_2</i><br>$lee_news_onoff</p><br />
        <p><i>$lee_news_text</i><br>$lee_news</p>
		 <p></p>
		<p>Release: $plug_rel</p>
		<p>Version: $plug_ver</p>

    </div>
    <hr>
</div>
__HTML;

echo $settings;