<?php
/* LiangLee News Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee News Manager
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File settings.php
 */
/**
* Get Version
**/ 
$plug_ver = LiangLee_version('LiangLeeNews');
$plug_rel = LiangLee_release('LiangLeeNews');

/**
* Resgister Languages
**/
$lee_news_text = elgg_echo('leenews:1');
$lee_news_text_2 = elgg_echo('lee:news:off:on');
$lee_news_text_page = elgg_echo('lee:news:page:spage');

$lee_news_h1 = elgg_echo('lee:news:page:con');
$lee_news_h2 = elgg_echo('lee:news:page:news');
$lee_news_h3 = elgg_echo('lee:news:page:page');



/**
* Resgister Settings
**/

$lee_news = elgg_view("input/longtext", array(
"name" => "params[LiangLee_news]", 
"placeholder" => "This is news",
"value" => $vars['entity']->LiangLee_news
));
$lee_news_onoff = elgg_view('input/dropdown', array(
    'name' => 'params[LiangLee_news_onoff]',
    'value' => $vars['entity']->LiangLee_news_onoff,
    'options_values' => array(
	'1' => 'Enable News', 
	'0' => 'Disable News'
)));
$lee_news_page = elgg_view('input/text', array(
    'name' => 'params[LiangLee_news_page]',
    'value' => $vars['entity']->LiangLee_news_page,
    'placeholder' => "dashboard",
));
$settings = <<<__HTML

    <div>
	<div class='elgg-module-inline'>
		<div class='elgg-head'>
		<h3>$lee_news_h1</h3></div></div>
		<p><i>$lee_news_text_2</i><br>$lee_news_onoff</p><br />
			<div class='elgg-module-inline'>
		<div class='elgg-head'>
		<h3>$lee_news_h2</h3></div></div>
        <p><i>$lee_news_text</i><br>$lee_news</p><br />
			<div class='elgg-module-inline'>
		<div class='elgg-head'>
		<h3>Display on specfic page</h3></div></div>
        <p><i>$lee_news_text_page</i><br>$lee_news_page</p>
		    <hr>
		 <p></p>
		<p>Release: $plug_rel</p>
		<p>Version: $plug_ver</p>

    </div>
    <hr>
</div>
__HTML;

echo $settings;