<?php
/** LiangLee News Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee News Manager
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File css.php
 */
?>
#LIANGLEECSSNEWS01{ margin-top:20px;padding:20px;background:#fff9e2;border:3px dashed #dad1b0;text-align:center;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}
