<?php
/* LiangLee News Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee News Manager
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeeNews.php
 */
function LiangLeeNews_lib(){
/*
 * Register Global Variables.
 *
 * @access public
 */
/*
 * Register Global Variables for News.
 *
 * @access public
 */
global $leenews;
/*
 * Fetch Settings for news.
 *
 * @access public
 */
$lee_news = elgg_get_plugin_setting("LiangLee_news", "LiangLeeNews");
if(!$lee_news){
$leenews = elgg_echo('leenews:nos');
} else {
$leenews =  $lee_news;
}
}
?>